;;; Packages for theorem provers
;;;
;;; SPDX-FileCopyrightText: 2025 Nguyễn Gia Phong
;;; SPDX-License-Identifier: GPL-3.0-or-later

(define-module (loftix deduction)
  #:use-module (gnu packages)
  #:use-module (gnu packages check)
  #:use-module (gnu packages digest)
  #:use-module (gnu packages maths)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python-build)
  #:use-module (guix build-system cmake)
  #:use-module (guix build-system pyproject)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages))

(define z3-for-fuzzolic
  (let* ((base z3)
         (base-version "4.14.1")
         (base-tag (string-append "z3-" base-version))
         (revision "fuzzolic")
         (commit "8a9e291dc2117e5cf48bdf2810f254000c6dd3d9")
         (upstream "https://github.com/Z3Prover/z3"))
    (package
      (inherit base)
      (name "z3-for-fuzzolic")
      (version (git-version base-version revision commit))
      (source
       (origin
         (inherit (package-source base))
         (uri (git-reference (url upstream)
                             (commit base-tag)))
         (file-name (git-file-name name version))
         (sha256
          (base32 "1gdknrqnnigfh1h833ks3vbrp4j74mfg6188c0k4xbl5zv6h6fx5"))
         (patches
          (list
            (origin
              (method url-fetch)
              (uri (string-append upstream "/compare/" base-tag
                                  ".." commit ".diff"))
              (sha256
               (base32 "1qgfz4rz4xm1ivr5s0wz5d16mc1gr5yyc400sfbxm8r288pb56bq"))
              (file-name (string-append name ".patch")))))))
      (home-page "https://github.com/season-lab/z3")
      (synopsis "Z3 for FUZZOLIC"))))

(define-public fuzzy-sat
  (let ((commit "5939b998a28ce2017b2c0dd89434792ab9ce5e51"))
    (package
      (name "fuzzy-sat")
      (version (git-version "0.1" "master" commit))
      (home-page "https://github.com/season-lab/fuzzy-sat")
      (source
       (origin
         (method git-fetch)
         (uri (git-reference (url home-page)
                            (commit commit)))
         (file-name (git-file-name name version))
         (sha256
          (base32 "1wm8sznv9w09vfb6nk1c4kbych34zpiywxkz37az81wsvpbwk82s"))
         (patches (search-patches "patches/fuzzy-sat-include.patch"
                                  "patches/fuzzy-sat-unbundle.patch"
                                  "patches/fuzzy-sat-install.patch"))))
      (build-system cmake-build-system)
      (arguments
       '(#:phases (modify-phases %standard-phases
                    (replace 'check
                      (lambda* (#:key source tests? #:allow-other-keys)
                        (when (not tests?)
                          (setenv "FUZZY_BIN" "tools/fuzzy-solver")
                          (invoke "pytest" "-p" "no:cacheprovider" "-v"
                                  (string-append source "/tests/run.py"))))))))
      (native-inputs (list pkg-config python-pytest))
      (inputs (list xxhash z3-for-fuzzolic))
      (synopsis "Approximate solver for concolic execution")
      (description "Fuzzy SAT is an approximate solver that borrows ideas
from the fuzzing domain.  It is tailored to the symbolic expressions
generated by concolic engines and can replace classic SMT solvers
in this context.  By analyzing the expressions contained in symbolic queries,
Fuzzy SAT performs informed mutations to possibly generate
new valuable inputs.")
      (license license:gpl2+))))
