name: Check REUSE compliance
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v4
    - name: Install reuse
      run: sudo apt install reuse
    - name: Run reuse
      run: reuse lint
